# Generated by Django 3.2.5 on 2021-07-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryType', models.CharField(max_length=100)),
                ('categoryType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='db_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('subCategoryType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subcategories', to='db_app.subcategory')),
            ],
        ),
    ]
